import {
  AlignmentType,
  BorderStyle,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TabStopType,
  TextRun,
} from 'docx';
import type { CvDocument } from '../schema';
import { layoutCv, type Block } from './layout';
import { getTemplate, type TemplateStyle } from './templates';

/**
 * DOCX rendering.
 *
 * DOCX matters more than PDF for this product: most applicant tracking systems
 * parse Word documents more reliably than PDFs, and several still reject PDFs
 * outright. The output is deliberately plain — real headings, no tables, no
 * text boxes, no columns — because those are precisely the constructs that
 * make a CV extract as gibberish.
 */

/** DOCX sizes are half-points; positions are twips (1/20 pt). */
const halfPoints = (points: number): number => Math.round(points * 2);
const twips = (points: number): number => Math.round(points * 20);

export interface RenderOptions {
  readonly templateKey?: string;
}

export async function renderCvToDocx(
  cv: CvDocument,
  options: RenderOptions = {},
): Promise<Buffer> {
  const template = getTemplate(options.templateKey);
  const blocks = layoutCv(cv, template);

  const document = new Document({
    creator: 'JobPilot',
    title: `${cv.personal.fullName} — CV`,
    description: 'Generated by JobPilot',
    styles: {
      default: {
        document: {
          run: { font: template.fontFamily, size: halfPoints(template.baseFontSize) },
          paragraph: { spacing: { line: Math.round(template.lineSpacing * 240) } },
        },
      },
    },
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: twips(template.marginPoints),
              bottom: twips(template.marginPoints),
              left: twips(template.marginPoints),
              right: twips(template.marginPoints),
            },
          },
        },
        children: blocks.flatMap((block) => toParagraphs(block, template)),
      },
    ],
  });

  return Packer.toBuffer(document);
}

function toParagraphs(block: Block, template: TemplateStyle): Paragraph[] {
  switch (block.kind) {
    case 'name':
      return [
        new Paragraph({
          alignment: AlignmentType.LEFT,
          spacing: { after: twips(2) },
          children: [
            new TextRun({
              text: block.text,
              bold: true,
              size: halfPoints(template.nameFontSize),
              color: template.accentColour,
            }),
          ],
        }),
      ];

    case 'contact':
      return [
        new Paragraph({
          spacing: { after: twips(template.sectionSpacing) },
          children: [
            new TextRun({
              text: block.parts.join('  |  '),
              size: halfPoints(template.baseFontSize - 0.5),
              color: '444444',
            }),
          ],
        }),
      ];

    case 'heading':
      return [
        new Paragraph({
          // A real heading level, not bold body text: this is what lets an ATS
          // and a screen reader see the document's structure.
          heading: HeadingLevel.HEADING_2,
          spacing: { before: twips(template.sectionSpacing), after: twips(3) },
          ...(template.headingRule
            ? {
                border: {
                  bottom: { style: BorderStyle.SINGLE, size: 6, color: template.accentColour, space: 2 },
                },
              }
            : {}),
          children: [
            new TextRun({
              text: template.headingUppercase ? block.text.toUpperCase() : block.text,
              bold: true,
              size: halfPoints(template.headingFontSize),
              color: template.accentColour,
            }),
          ],
        }),
      ];

    case 'entry':
      return [
        new Paragraph({
          spacing: { before: twips(5), after: twips(1) },
          // A right tab stop rather than a table: dates line up on the right
          // margin and the text still extracts in reading order.
          tabStops: [{ type: TabStopType.RIGHT, position: twips(468) }],
          children: [
            new TextRun({ text: block.primary, bold: true, size: halfPoints(template.baseFontSize + 0.5) }),
            // An em dash rather than two spaces. It reads better, and it keeps
            // the pair recoverable: extracted back out of the file, "Senior
            // Engineer Acme" cannot be split into a title and an employer
            // again, whereas "Senior Engineer — Acme" can.
            ...(block.secondary
              ? [new TextRun({ text: ` — ${block.secondary}`, italics: true, color: '444444' })]
              : []),
            ...(block.trailing ? [new TextRun({ text: `\t${block.trailing}`, color: '444444' })] : []),
          ],
        }),
      ];

    case 'bullet':
      return [
        new Paragraph({
          bullet: { level: 0 },
          spacing: { after: twips(1) },
          children: [new TextRun({ text: block.text })],
        }),
      ];

    case 'paragraph':
      return [
        new Paragraph({
          spacing: { after: twips(3) },
          children: [new TextRun({ text: block.text })],
        }),
      ];
  }
}
