import { Inject, Injectable, Logger } from '@nestjs/common';
import { createHash, createHmac, randomUUID } from 'node:crypto';
import { mkdir, readFile, unlink, writeFile } from 'node:fs/promises';
import { dirname, join, resolve, sep } from 'node:path';
import { ENV, type Env } from '../../config/config.module';
import { AppException } from '../../common/errors/app-exception';

/**
 * File storage.
 *
 * Two drivers behind one interface: the local disk for development, and S3 for
 * anywhere the filesystem does not survive a redeploy — which includes every
 * container platform and every serverless host.
 *
 * Nothing here trusts the client. The stored name is generated, never the
 * user's; the directory is confined; and the caller is expected to have
 * sniffed the content type from the bytes rather than the extension.
 */

export interface StoredFile {
  readonly storageKey: string;
  readonly sizeBytes: number;
  readonly checksumSha256: string;
}

export interface PutOptions {
  readonly userId: string;
  readonly content: Buffer;
  readonly extension: string;
}

@Injectable()
export class StorageService {
  private readonly logger = new Logger(StorageService.name);
  private readonly root: string;

  constructor(@Inject(ENV) private readonly env: Env) {
    this.root = resolve(env.STORAGE_LOCAL_PATH);
  }

  get driver(): 'LOCAL' | 'S3' {
    return this.env.STORAGE_DRIVER === 's3' ? 'S3' : 'LOCAL';
  }

  /**
   * Writes a file and returns its key and checksum.
   *
   * The key is `<userId>/<uuid>.<ext>`, so the user's own id partitions the
   * store and the filename carries nothing an attacker chose. A user-supplied
   * name reaching the filesystem is how path traversal happens; the original
   * is kept in the database as metadata instead.
   */
  async put(options: PutOptions): Promise<StoredFile> {
    const checksum = createHash('sha256').update(options.content).digest('hex');
    const safeExtension = options.extension.replace(/[^a-z0-9]/gi, '').slice(0, 8) || 'bin';
    const storageKey = `${options.userId}/${randomUUID()}.${safeExtension}`;

    if (this.driver === 'S3') {
      await this.putToS3(storageKey, options.content);
    } else {
      const target = this.resolveLocal(storageKey);
      await mkdir(dirname(target), { recursive: true });
      await writeFile(target, options.content);
    }

    return { storageKey, sizeBytes: options.content.byteLength, checksumSha256: checksum };
  }

  async get(storageKey: string): Promise<Buffer> {
    if (this.driver === 'S3') return this.getFromS3(storageKey);
    return readFile(this.resolveLocal(storageKey));
  }

  /**
   * Deletion is best-effort. An orphaned blob costs storage; a failed delete
   * that aborts the surrounding transaction costs the user their action.
   */
  async remove(storageKey: string): Promise<void> {
    try {
      if (this.driver === 'S3') {
        await this.removeFromS3(storageKey);
        return;
      }
      await unlink(this.resolveLocal(storageKey));
    } catch (error) {
      this.logger.warn(
        `Could not delete ${storageKey}: ${error instanceof Error ? error.message : 'unknown error'}`,
      );
    }
  }

  /**
   * Resolves a key inside the storage root, refusing anything that escapes it.
   *
   * Keys are generated by `put`, so traversal should be impossible — but a key
   * also arrives from the database, and this is the last point before a path
   * reaches the filesystem. Checking here is cheap and does not depend on
   * every future caller being careful.
   */
  private resolveLocal(storageKey: string): string {
    const target = resolve(join(this.root, storageKey));
    if (target !== this.root && !target.startsWith(this.root + sep)) {
      throw AppException.internal('INTERNAL_ERROR', 'Refusing to access a path outside the storage root.');
    }
    return target;
  }

  private s3Config(): { endpoint: string; region: string; bucket: string; accessKeyId: string; secretAccessKey: string } {
    const { S3_ENDPOINT, S3_REGION, S3_BUCKET, S3_ACCESS_KEY_ID, S3_SECRET_ACCESS_KEY } = this.env;

    if (!S3_BUCKET || !S3_ACCESS_KEY_ID || !S3_SECRET_ACCESS_KEY) {
      // Fails at the point of use with a specific message rather than at boot,
      // because S3 is optional and a local deployment must still start.
      throw AppException.internal(
        'INTERNAL_ERROR',
        'STORAGE_DRIVER is s3 but S3_BUCKET, S3_ACCESS_KEY_ID or S3_SECRET_ACCESS_KEY is missing.',
      );
    }

    return {
      endpoint: S3_ENDPOINT ?? `https://s3.${S3_REGION ?? 'us-east-1'}.amazonaws.com`,
      region: S3_REGION ?? 'us-east-1',
      bucket: S3_BUCKET,
      accessKeyId: S3_ACCESS_KEY_ID,
      secretAccessKey: S3_SECRET_ACCESS_KEY,
    };
  }

  /*
   * The S3 driver is intentionally a thin, dependency-free signer rather than
   * the AWS SDK: the SDK is a large dependency for three operations, and this
   * keeps the serverless bundle small. It speaks plain SigV4 over fetch, so it
   * also works against S3-compatible services (R2, MinIO, Spaces).
   */

  private async putToS3(storageKey: string, content: Buffer): Promise<void> {
    const { bucket, endpoint } = this.s3Config();
    const response = await this.signedS3Request('PUT', `${endpoint}/${bucket}/${storageKey}`, content);
    if (!response.ok) {
      throw AppException.internal('INTERNAL_ERROR', `S3 upload failed with HTTP ${response.status}.`);
    }
  }

  private async getFromS3(storageKey: string): Promise<Buffer> {
    const { bucket, endpoint } = this.s3Config();
    const response = await this.signedS3Request('GET', `${endpoint}/${bucket}/${storageKey}`);
    if (!response.ok) {
      throw AppException.notFound('NOT_FOUND', 'The stored file could not be read.');
    }
    return Buffer.from(await response.arrayBuffer());
  }

  private async removeFromS3(storageKey: string): Promise<void> {
    const { bucket, endpoint } = this.s3Config();
    await this.signedS3Request('DELETE', `${endpoint}/${bucket}/${storageKey}`);
  }

  private async signedS3Request(
    method: 'GET' | 'PUT' | 'DELETE',
    url: string,
    body?: Buffer,
  ): Promise<Response> {
    const { region, accessKeyId, secretAccessKey } = this.s3Config();
    const parsed = new URL(url);

    const now = new Date();
    const amzDate = now.toISOString().replace(/[:-]|\.\d{3}/g, '');
    const dateStamp = amzDate.slice(0, 8);
    const payloadHash = createHash('sha256')
      .update(body ?? Buffer.alloc(0))
      .digest('hex');

    const canonicalHeaders =
      `host:${parsed.host}\n` + `x-amz-content-sha256:${payloadHash}\n` + `x-amz-date:${amzDate}\n`;
    const signedHeaders = 'host;x-amz-content-sha256;x-amz-date';

    const canonicalRequest = [
      method,
      parsed.pathname,
      '',
      canonicalHeaders,
      signedHeaders,
      payloadHash,
    ].join('\n');

    const scope = `${dateStamp}/${region}/s3/aws4_request`;
    const stringToSign = [
      'AWS4-HMAC-SHA256',
      amzDate,
      scope,
      createHash('sha256').update(canonicalRequest).digest('hex'),
    ].join('\n');

    const signature = hmacChain(secretAccessKey, dateStamp, region, stringToSign);

    return fetch(url, {
      method,
      headers: {
        Authorization: `AWS4-HMAC-SHA256 Credential=${accessKeyId}/${scope}, SignedHeaders=${signedHeaders}, Signature=${signature}`,
        'x-amz-content-sha256': payloadHash,
        'x-amz-date': amzDate,
      },
      ...(body ? { body: new Uint8Array(body) } : {}),
    });
  }
}

/** The SigV4 key derivation chain. */
function hmacChain(secret: string, dateStamp: string, region: string, stringToSign: string): string {
  const sign = (key: Buffer | string, data: string): Buffer =>
    createHmac('sha256', key).update(data).digest();

  const dateKey = sign(`AWS4${secret}`, dateStamp);
  const regionKey = sign(dateKey, region);
  const serviceKey = sign(regionKey, 's3');
  const signingKey = sign(serviceKey, 'aws4_request');

  return createHmac('sha256', signingKey).update(stringToSign).digest('hex');
}
